apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 490874679766.dkr.ecr.us-east-1.amazonaws.com/site-frontend:7692b67ea54218fff9aa9a036d7089c40c479607
          ports:
            - containerPort: 8501
